<!DOCTYPE html>
<html lang="zxx">
<head>
	<title><?php echo TITLE ?></title>
	<meta charset="UTF-8">
	<meta name="description" content="Real estate html template">
	<meta name="keywords" content="real estate, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="<?php echo DOMAIN ?>assets/img/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Sarabun:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/font-awesome.min.css"/>
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/flaticon.css"/>
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/magnific-popup.css"/>
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/owl.carousel.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/style.css"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>
	
	<!-- Header section -->
	<header class="header-section">
		<!-- logo -->
		<a href="<?=DOMAIN?>" class="site-logo">
			<img src="<?php echo DOMAIN ?>assets/img/logo.png" alt="">
		</a>
		<div class="nav-switch">
			<i class="fa fa-bars"></i>
		</div>
		<div class="container">
			<ul class="main-menu">
				<li><a href="home">Home</a></li>
				<li><a href="about">About Us</a></li>
				<li><a href="housing">Housing</a></li>
				<li><a href="contact">Contact</a></li>
			</ul>
		</div>
	</header>
	<!-- Header section end -->