<?php	
	$info = [];
	$data = $this->view_data['info'];
	$alert = $this->view_data['alert'];
	foreach($data as $row){
		$feature_name = $row['feature_name'];
		$feature_val = $row['value'];
		$info[$feature_name] = $feature_val;
	}
?>
<style>
[x-cloak] {
  display: none;
}
</style>
<script>
function remove(me) {
  var element = document.getElementById("alert");
  element.remove();
}
</script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
<?php
if($alert == 'Success'){
	echo '<div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Successful!</strong>
			  <span class="block sm:inline">Website has been updated.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert") ">
				<svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
if($alert == 'Failed'){
	echo '<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Failed,</strong>
			  <span class="block sm:inline"> please try again.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert")">
				<svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
?>
<main class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<button class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="document.getElementById('myForm').submit();">
			<h4 class="px-1 font-medium text-white">Save & Publish</h4>
		</button>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<form action="<?php echo DOMAIN ?>admin/aboutpage" method="post" id="myForm" class="p-4 flex flex-col">
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Header</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Header" type="text" placeholder="Enter name Here" value="<?=$info['Header'];?>">
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Content</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Content" type="text" placeholder="Enter Description Here" ><?=$info['Content'];?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Residential Developed</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Residential Developed" type="text" placeholder="Enter name Here" value="<?=$info['Residential Developed'];?>">
					</div>
					
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Homes Builded</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Homes Builded" type="text" placeholder="Enter name Here" value="<?=$info['Homes Builded'];?>">
					
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Statisfied Custumers</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Statisfied Custumers" type="text" placeholder="Enter Description Here"><?=$info['Statisfied Custumers'];?></textarea>
					</div>
					
					<br><br>
				</form>
			</div>
		</div>
		
		<div class="flex-col flex-1 md:ml-2 md:w-1/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<div class="p-4 flex flex-col">
					<h1 class="font-medium text-md mb-3">Hero Image</h1>
					<img src="<?=$info['AboutH Image'];?>" onclick="document.getElementById('file-input-1').click();" id="opnAboutHImage" name="AboutHImage" class="rounded-lg">
					<input id="file-input-1" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveUpload('AboutHImage','AboutH Image');">Upload</a>
					</div>
				</div>
			</div>
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<div class="p-4 flex flex-col">
				
					<h1 class="font-medium text-md mb-3">Slideshow Images</h1>
					<?php
						$slide_content = $info['Slide Image'];
						$slides = explode(";", $slide_content);
						$imag1 = '';
						$imag2 = '';
						$imag3 = '';
						$imag4 = '';
						foreach ($slides as $value) {
							if($imag1 == ''){
								$imag1 = $value;
							}elseif($imag2 == ''){
								$imag2 = $value;
							}elseif($imag3 == ''){
								$imag3 = $value;
							}elseif($imag4 == ''){
								$imag4 = $value;
							}
						}
					?>
					<img src="<?=$imag1?>" onclick="document.getElementById(`file-input-4`).click();" id="opnSlideshowImage1" name="abtslide1" class="rounded-lg">
					<input id="file-input-4" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('abtslide1','Slide Image');">Upload</a>
					</div>
					<img src="<?=$imag2?>" onclick="document.getElementById(`file-input-5`).click();" id="opnSlideshowImage2" name="abtslide2" class="rounded-lg">
					<input id="file-input-5" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('abtslide2','Slide Image');">Upload</a>
					</div>
					<img src="<?=$imag3?>" onclick="document.getElementById(`file-input-6`).click();" id="opnSlideshowImage3" name="abtslide3" class="rounded-lg">
					<input id="file-input-6" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('abtslide3','Slide Image');">Upload</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		const reader = new FileReader();
		const fileInput1 = document.getElementById("file-input-1");
		const img1 = document.getElementById("opnAboutHImage");
		
		const readerx = new FileReader();
		const fileInput4 = document.getElementById("file-input-4");
		const img4 = document.getElementById("opnSlideshowImage1");
		const fileInput5 = document.getElementById("file-input-5");
		const img5 = document.getElementById("opnSlideshowImage2");
		const fileInput6 = document.getElementById("file-input-6");
		const img6 = document.getElementById("opnSlideshowImage3");
		
		let changestsimg = 1;
		
		function saveUpload(namedImage, fieldname){
			var formData = new FormData();
			formData.append('imname', namedImage);
			formData.append('fdname', fieldname);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/saveabtimage", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Saved');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to save Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again later');
					}
				}
			};
			xhr.send(formData);
		}
		
		function saveSlideUpload(namedImage, fieldname){
			console.log(namedImage);
			var formData = new FormData();
			formData.append('imname', namedImage);
			formData.append('fdname', fieldname);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/saveslide", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					console.log(xhr);
					console.log(xhr.responseText);
					if(xhr.responseText == 'success'){
						alert('Image has been Saved');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to save Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again later');
					}
				}
			};
			xhr.send(formData);
		}
		
		reader.onload = e => {
			img1.src = e.target.result;
			
			var formData = new FormData();
			formData.append('imname', img1.name);
			formData.append("files", fileInput1.files[0]);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/uploads", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Loaded');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to Load Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again');
					}
				}
			};
			xhr.send(formData);
		}
		fileInput1.addEventListener('change', e => {
		  const f = e.target.files[0];
		  reader.readAsDataURL(f);
		})
		
		readerx.onload = e => {
			let img_valname = '';
			if(changestsimg == 1){
				img4.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img4.name);
				formData.append("files", fileInput4.files[0]);
			}
			if(changestsimg == 2){
				img5.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img5.name);
				formData.append("files", fileInput5.files[0]);
			}
			if(changestsimg == 3){
				img6.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img6.name);
				formData.append("files", fileInput6.files[0]);
			}
			if(changestsimg == 4){
				img7.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img7.name);
				formData.append("files", fileInput7.files[0]);
			}
			
			
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/uploads", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Loaded');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to Load Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again');
					}
				}
			};
			xhr.send(formData);
		}
		fileInput4.addEventListener('change', e => {
		  changestsimg = 1;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
		fileInput5.addEventListener('change', e => {
		  changestsimg = 2;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
		fileInput6.addEventListener('change', e => {
		  changestsimg = 3;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
	</script>
</main>