<main class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<button class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="document.getElementById('myForm').submit();">
			<h4 class="px-1 font-medium text-white">Save</h4>
		</button>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<form action="<?php echo DOMAIN ?>admin/home/changepwd" method="post" id="myForm" class="p-4 flex flex-col" enctype="multipart/form-data">
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Password</label>
						<input name="user_id" type="text" value="<?php if(!empty($_GET['id'])){echo $_GET['id'];}else{header('location: '.DOMAIN.'admin/home');}?>" 
						hidden
						required>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="pwd" type="password" placeholder="Enter password" required>
					</div>
					<br><br>
				</form>
			</div>
		</div>
	</div>
</main>