<?php	
	$info = [];
	$data = $this->view_data['info'];
	$alert = $this->view_data['alert'];
	foreach($data as $row){
		$feature_name = $row['feature_name'];
		$feature_val = $row['value'];
		$info[$feature_name] = $feature_val;
	}
?>
<style>
[x-cloak] {
  display: none;
}
</style>
<script>
function remove(me) {
  var element = document.getElementById("alert");
  element.remove();
}
</script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
<?php
if($alert == 'Success'){
	echo '<div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Successful!</strong>
			  <span class="block sm:inline">Website has been updated.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert") ">
				<svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
if($alert == 'Failed'){
	echo '<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Failed,</strong>
			  <span class="block sm:inline"> please try again.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert")">
				<svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
?>
<main class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<button class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="document.getElementById('myForm').submit();">
			<h4 class="px-1 font-medium text-white">Save & Publish</h4>
		</button>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<form action="<?php echo DOMAIN ?>admin/company" method="post" id="myForm" class="p-4 flex flex-col">
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Company Name</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Company Name" type="text" placeholder="Enter name Here" value="<?=$info['Company Name'];?>">
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Telephone</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Telephone" type="text" placeholder="Enter Description Here" ><?=$info['Telephone'];?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Email</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Email" type="text" placeholder="Enter name Here" value="<?=$info['Email'];?>">
					</div>
					
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Address</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Address" type="text" placeholder="Enter name Here" value="<?=$info['Address'];?>">
					
					</div>
					 
					<br><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Facebook</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="facebook" type="text" placeholder="Enter name Here" value="<?=$info['facebook'];?>">
					
					</div>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Instagram</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="instagram" type="text" placeholder="Enter name Here" value="<?=$info['instagram'];?>">
					
					</div>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Twitter</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="twitter" type="text" placeholder="Enter name Here" value="<?=$info['twitter'];?>">
					
					</div>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">LinkedIn</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="linkedin" type="text" placeholder="Enter name Here" value="<?=$info['linkedin'];?>">
					
					</div>
				</form>
			</div>
		</div>
		
		 
	</div>
	
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<a href="<?=DOMAIN?>admin/company/newstaff" class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md">
			<h4 class="px-1 font-medium text-white">Create New Staff</h4>
		</a>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<table class="min-w-full divide-y divide-gray-200">
					<thead class="bg-gray-50">
						<tr>
						  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Name
						  </th>
						  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Title
						  </th>
						  <th scope="col" class="relative px-6 py-3">
							<span class="sr-only">Edit</span>
						  </th>
						</tr>
					</thead>
					<tbody class="bg-white divide-y divide-gray-200">
						<?php
							$staff = $this->view_data['staff'];
							foreach ($staff as $value) {
								echo '<tr>
										  <td class="px-6 py-4 whitespace-nowrap">
											<div class="flex items-center">
											  <div class="flex-shrink-0 h-10 w-10">
												<img class="h-10 w-10 rounded-full" src="'.$value['image'].'" alt="">
											  </div>
											  <div class="ml-4">
												<div class="text-sm font-medium text-gray-900">
												  '.$value['fullname'].'
												</div>
											  </div>
											</div>
										  </td>
										  <td class="px-6 py-4 whitespace-nowrap">
											<div class="text-sm text-gray-900">'.$value['position'].'</div>
										  </td>
										  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
											<a href="company/newstaff?id='.$value['id'].'" class="text-indigo-600 hover:text-indigo-900">Edit</a>
											<a href="company/remstaff?id='.$value['id'].'" class="text-red-600 hover:text-red-900">Delete</a>
										  </td>
										</tr>';
							}
						?>
						
					<!-- More people... -->
					</tbody>
				</table>
			</div>
		</div>
	</div>
	 
</main>