<?php	
	$info = [];
	$data = $this->view_data['info'];
	$alert = $this->view_data['alert'];
	foreach($data as $row){
		$feature_name = $row['feature_name'];
		$feature_val = $row['value'];
		$info[$feature_name] = $feature_val;
	}
?>
<style>
[x-cloak] {
  display: none;
}
</style>
<script>
function remove(me) {
  var element = document.getElementById("alert");
  element.remove();
}
</script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
<?php
if($alert == 'Success'){
	echo '<div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Successful!</strong>
			  <span class="block sm:inline">Website has been updated.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert") ">
				<svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
if($alert == 'Failed'){
	echo '<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Failed,</strong>
			  <span class="block sm:inline"> please try again.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert")">
				<svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
?>
<main class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<button class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="document.getElementById('myForm').submit();">
			<h4 class="px-1 font-medium text-white">Save & Publish</h4>
		</button>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<form action="<?php echo DOMAIN ?>admin/homepage" method="post" id="myForm" class="p-4 flex flex-col">
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Hero Header</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Hero Header" type="text" placeholder="Enter name Here" value="<?=$info['Hero Header'];?>">
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Hero Paragraph</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Hero Subtitle" type="text" placeholder="Enter Description Here" ><?=$info['Hero Subtitle'];?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Promo House 1 Header</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Promo House1 Header" type="text" placeholder="Enter name Here" value="<?=$info['Promo House1 Header'];?>">
					</div>
					
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Promo House 1 Button Link</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Promo House1 Button" type="text" placeholder="Enter name Here" value="<?=$info['Promo House1 Button'];?>">
					
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Promo House 1 Paragraph</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Promo House1 Quote" type="text" placeholder="Enter Description Here"><?=$info['Promo House1 Quote'];?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Promo House 2 Header</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Promo House2 Header" type="text" placeholder="Enter name Here" value="<?=$info['Promo House2 Header'];?>">
					</div>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Promo House 2 Button Link</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Promo House2 Button" type="text" placeholder="Enter name Here" value="<?=$info['Promo House2 Button'];?>">
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Promo House 2 Paragraph</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Promo House2 Quote" type="text" placeholder="Enter Description Here"><?=$info['Promo House2 Quote'];?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Slideshow Title 1</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Showroom Title1" type="text" placeholder="Enter name Here" value="<?=$info['Showroom Title1'];?>">
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Slideshow Paragraph 1</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Showroom Quote1" type="text" placeholder="Enter Description Here"><?=$info['Showroom Quote1'];?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Slideshow Title 2</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Showroom Title2" type="text" placeholder="Enter name Here" value="<?=$info['Showroom Title2'];?>">
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Slideshow Paragraph 2</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Showroom Quote2" type="text" placeholder="Enter Description Here"><?=$info['Showroom Quote2'];?></textarea>
					</div>
	
					<br><br>
				</form>
			</div>
		</div>
		
		<div class="flex-col flex-1 md:ml-2 md:w-1/5">
		
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<div class="p-4 flex flex-col">
					<h1 class="font-medium text-md mb-3">Hero Image</h1>
					<img src="<?=$info['Hero Image'];?>" onclick="document.getElementById('file-input-1').click();" id="opnHeroImage" name="HeroImage" class="rounded-lg">
					<input id="file-input-1" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveUpload('HeroImage','Hero Image');">Upload</a>
						<!--<a href="testpage?content=home&img=HeroImage" target="_blank" class="float-right hover:text-blue-500 flex items-center my-2 px-4 py-2">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
							</svg>
							Preview on Website
						</a>-->
					</div>
				</div>
			</div>
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<div class="p-4 flex flex-col">
					<h1 class="font-medium text-md mb-3">Promo House1 Image</h1>
					<img src="<?=$info['Promo House1 Image'];?>" onclick="document.getElementById('file-input-2').click();" id="opnPromoHouse1Image" name="PromoHouse1Image" class="rounded-lg">
					<input id="file-input-2" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveUpload('PromoHouse1Image','Promo House1 Image');">Upload</a>
						<!--<a href="testpage?content=home&img=PromoHouse1Image" target="_blank" class="float-right hover:text-blue-500 flex items-center my-2 px-4 py-2">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
							</svg>
							Preview on Website
						</a>-->
					</div>
				</div>
			</div>
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<div class="p-4 flex flex-col">
					<h1 class="font-medium text-md mb-3">Promo House2 Image</h1>
					<img src="<?=$info['Promo House2 Image'];?>" onclick="document.getElementById('file-input-3').click();" id="opnPromoHouse2Image" name="PromoHouse2Image" class="rounded-lg">
					<input id="file-input-3" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveUpload('PromoHouse2Image','Promo House2 Image');">Upload</a>
						<!--<a href="testpage?content=home&img=PromoHouse2Image" target="_blank" class="float-right hover:text-blue-500 flex items-center my-2 px-4 py-2">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
							</svg>
							Preview on Website
						</a>-->
					</div>
				</div>
			</div>
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<div class="p-4 flex flex-col">
				
					<h1 class="font-medium text-md mb-3">Slideshow Images</h1>
					<?php
						$slide_content = $info['Showroom Image'];
						$slides = explode(";", $slide_content);
						$imag1 = '';
						$imag2 = '';
						$imag3 = '';
						$imag4 = '';
						foreach ($slides as $value) {
							if($imag1 == ''){
								$imag1 = $value;
							}elseif($imag2 == ''){
								$imag2 = $value;
							}elseif($imag3 == ''){
								$imag3 = $value;
							}elseif($imag4 == ''){
								$imag4 = $value;
							}
						}
					?>
					<img src="<?=$imag1?>" onclick="document.getElementById(`file-input-4`).click();" id="opnSlideshowImage1" name="slide1" class="rounded-lg">
					<input id="file-input-4" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('slide1','Showroom Image');">Upload</a>
					</div>
					<img src="<?=$imag2?>" onclick="document.getElementById(`file-input-5`).click();" id="opnSlideshowImage2" name="slide2" class="rounded-lg">
					<input id="file-input-5" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('slide2','Showroom Image');">Upload</a>
					</div>
					<img src="<?=$imag3?>" onclick="document.getElementById(`file-input-6`).click();" id="opnSlideshowImage3" name="slide3" class="rounded-lg">
					<input id="file-input-6" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('slide3','Showroom Image');">Upload</a>
					</div>
					<img src="<?=$imag4?>" onclick="document.getElementById(`file-input-7`).click();" id="opnSlideshowImage4" name="slide4" class="rounded-lg">
					<input id="file-input-7" type="file" accept="image/*" name="name" style="display: none;" />
					<div class="flex flex-row-reverse space-x-4 space-x-reverse">
						<a href="#" class="float-right bg-blue-600 hover:bg-blue-300 flex text-white items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="saveSlideUpload('slide4','Showroom Image');">Upload</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		const reader = new FileReader();
		const fileInput1 = document.getElementById("file-input-1");
		const img1 = document.getElementById("opnHeroImage");
		const reader0 = new FileReader();
		const fileInput2 = document.getElementById("file-input-2");
		const img2 = document.getElementById("opnPromoHouse1Image");
		const reader9 = new FileReader();
		const fileInput3 = document.getElementById("file-input-3");
		const img3 = document.getElementById("opnPromoHouse2Image");
		const readerx = new FileReader();
		const fileInput4 = document.getElementById("file-input-4");
		const img4 = document.getElementById("opnSlideshowImage1");
		const fileInput5 = document.getElementById("file-input-5");
		const img5 = document.getElementById("opnSlideshowImage2");
		const fileInput6 = document.getElementById("file-input-6");
		const img6 = document.getElementById("opnSlideshowImage3");
		const fileInput7 = document.getElementById("file-input-7");
		const img7 = document.getElementById("opnSlideshowImage4");
		let changestsimg = 1;
		
		function saveUpload(namedImage, fieldname){
			var formData = new FormData();
			formData.append('imname', namedImage);
			formData.append('fdname', fieldname);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/saveimage", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Saved');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to save Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again later');
					}
				}
			};
			xhr.send(formData);
		}
		
		function saveSlideUpload(namedImage, fieldname){
			console.log(namedImage);
			var formData = new FormData();
			formData.append('imname', namedImage);
			formData.append('fdname', fieldname);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/saveslide", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					console.log(xhr);
					console.log(xhr.responseText);
					if(xhr.responseText == 'success'){
						alert('Image has been Saved');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to save Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again later');
					}
				}
			};
			xhr.send(formData);
		}
		
		reader.onload = e => {
			img1.src = e.target.result;
			
			var formData = new FormData();
			formData.append('imname', img1.name);
			formData.append("files", fileInput1.files[0]);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/uploads", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Loaded');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to Load Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again');
					}
				}
			};
			xhr.send(formData);
		}
		fileInput1.addEventListener('change', e => {
		  const f = e.target.files[0];
		  reader.readAsDataURL(f);
		})
		
		reader0.onload = e => {
			img2.src = e.target.result;
			
			var formData = new FormData();
			formData.append('imname', img2.name);
			formData.append("files", fileInput2.files[0]);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/uploads", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Loaded');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to Load Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again');
					}
				}
			};
			xhr.send(formData);
		}
		fileInput2.addEventListener('change', e => {
		  const f = e.target.files[0];
		  reader0.readAsDataURL(f);
		})
		
		reader9.onload = e => {
			img3.src = e.target.result;
			
			var formData = new FormData();
			formData.append('imname', img3.name);
			formData.append("files", fileInput3.files[0]);
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/uploads", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Loaded');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to Load Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again');
					}
				}
			};
			xhr.send(formData);
		}
		fileInput3.addEventListener('change', e => {
		  const f = e.target.files[0];
		  reader9.readAsDataURL(f);
		})
		
		readerx.onload = e => {
			let img_valname = '';
			if(changestsimg == 1){
				img4.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img4.name);
				formData.append("files", fileInput4.files[0]);
			}
			if(changestsimg == 2){
				img5.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img5.name);
				formData.append("files", fileInput5.files[0]);
			}
			if(changestsimg == 3){
				img6.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img6.name);
				formData.append("files", fileInput6.files[0]);
			}
			if(changestsimg == 4){
				img7.src = e.target.result;
				var formData = new FormData();
				formData.append('imname', img7.name);
				formData.append("files", fileInput7.files[0]);
			}
			
			
			
			var xhr = new XMLHttpRequest();
			xhr.open('POST', "<?=DOMAIN?>admin/uploads", true);
			xhr.onreadystatechange = function(){
				if(xhr.readyState == 4 && xhr.status == 200){
					if(xhr.responseText == 'success'){
						alert('Image has been Loaded');
					}
					if(xhr.responseText == 'failed'){
						alert('Failed to Load Image');
					}
					if(xhr.responseText == 'error'){
						alert('Error, please try again');
					}
				}
			};
			xhr.send(formData);
		}
		fileInput4.addEventListener('change', e => {
		  changestsimg = 1;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
		fileInput5.addEventListener('change', e => {
		  changestsimg = 2;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
		fileInput6.addEventListener('change', e => {
		  changestsimg = 3;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
		fileInput7.addEventListener('change', e => {
		  changestsimg = 4;
		  const f = e.target.files[0];
		  readerx.readAsDataURL(f);
		})
	</script>
</main>