<?php	
	$houses = $this->view_data['num_house'];
	$accounts = $this->view_data['accounts'];
?>
<div class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
        <div class="flex flex-col lg:flex-row w-full lg:space-x-2 space-y-2 lg:space-y-0 mb-2 lg:mb-4">
            <div class="w-full lg:w-1/4">
                <div class="widget w-full p-4 shadow-sm rounded-lg bg-white border border-gray-100 dark:bg-gray-900 dark:border-gray-800">
                    <div class="flex flex-row items-center justify-between">
                        <div class="flex flex-col">
							<div class="text-xl font-bold">
                                <?=$houses?>
                            </div>
                            <div class="text-sm uppercase font-medium">
                                Houses on Listing
                            </div>
                        </div>
                        <svg class="stroke-current text-gray-500" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                            <polyline points="22 12 18 12 15 21 9 3 6 12 2 12">
                            </polyline>
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<a href="<?=DOMAIN?>admin/home/newuser" class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md">
			<h4 class="px-1 font-medium text-white">Create New Account</h4>
		</a>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<table class="min-w-full divide-y divide-gray-200">
					<thead class="bg-gray-50">
						<tr>
						  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Name
						  </th>
						  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Email
						  </th>
						  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
							Role
						  </th>
						  <th scope="col" class="relative px-6 py-3">
							<span class="sr-only">Edit</span>
						  </th>
						</tr>
					</thead>
					<tbody class="bg-white divide-y divide-gray-200">
						<?php
							foreach ($accounts as $value) {
								echo '<tr>
										  <td class="px-6 py-4 whitespace-nowrap">
											<div class="flex items-center">
											  <div class="ml-4">
												<div class="text-sm font-medium text-gray-900">
												  '.$value['name'].'
												</div>
											  </div>
											</div>
										  </td>
										  <td class="px-6 py-4 whitespace-nowrap">
											<div class="text-sm text-gray-900">'.$value['email'].'</div>
										  </td>
										  <td class="px-6 py-4 whitespace-nowrap">
											<div class="text-sm text-gray-900">'.$value['role'].'</div>
										  </td>
										  <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
											<a href="home/changepwd?id='.$value['id'].'" class="text-indigo-600 hover:text-indigo-900">Change Password </a> |
											<a href="home/remuser?id='.$value['id'].'" class="text-red-600 hover:text-red-900">Delete</a>
										  </td>
										</tr>';
							}
						?>
						
					<!-- More people... -->
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>