<?php	
	$alert = $this->view_data['alert'];
	$staff = $this->view_data['staff'];
?>
<style>
[x-cloak] {
  display: none;
}
</style>
<script>
function remove(me) {
  var element = document.getElementById("alert");
  element.remove();
}
</script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
<?php
if($alert == 'Success'){
	echo '<div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Successful!</strong>
			  <span class="block sm:inline">Website has been updated.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert") ">
				<svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
if($alert == 'Failed'){
	echo '<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" id="alert" role="alert">
			  <strong class="font-bold">Failed,</strong>
			  <span class="block sm:inline"> please try again.</span>
			  <span class="absolute top-0 bottom-0 right-0 px-4 py-3" onclick="remove("alert")">
				<svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
			  </span>
			</div>';
}
?>
<main class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
	<div class="flex flex-col justify-end lg:flex-row w-full  mb-2 lg:mb-4">
		<button class="float-right bg-green-500 hover:bg-green-700 flex items-center my-2 px-4 py-2 rounded-lg shadow-md" onclick="document.getElementById('myForm').submit();">
			<h4 class="px-1 font-medium text-white">Save & Publish</h4>
		</button>
	</div>
	<div class="flex flex-row w-full mb-2 lg:mb-4">
		<div class="flex-col flex-1 md:mr-2 md:w-4/5">
			<div class="rounded-lg shadow-sm bg-white mb-5">
				<form action="<?php echo DOMAIN ?>admin/company/newstaff" method="post" id="myForm" class="p-4 flex flex-col" enctype="multipart/form-data">
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Fullname</label>
						<?php 
							if(isset($_GET['id'])){
								echo '<input name="staff_id" type="text" value="'.$_GET['id'].'"  required >';
							}
						?>
						
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Fullname" type="text" placeholder="Enter name Here" value="<?php if(!empty($staff)){echo $staff['fullname'];}?>"  required >
					</div>
					<div class="w-full px-3 mb-6 h-20 md:mb-0">
						<label class="font-medium text-md mb-3">Description</label>
						<textarea class="appearance-none block h-20 w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Description" type="text" placeholder="Enter Description Here" required><?php if(!empty($staff)){echo $staff['about'];}?></textarea>
					</div>
					<br><br><hr><br>
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Position</label>
						<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="Position" type="text" placeholder="Enter name Here" value="<?php if(!empty($staff)){echo $staff['position'];}?>" required>
					</div>
					
					<div class="w-full px-3 mb-6 md:mb-0">
						<label class="font-medium text-md mb-3">Image</label>
						<input id="file-input" type="file" accept="image/*" name="staffimg" required />
					</div>
					 
					<br><br>
				</form>
			</div>
		</div>
	</div>
</main>