<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title><?php echo TITLE ?></title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="<?php echo DOMAIN ?>assets/img/favicon.ico" rel="shortcut icon"/>

	<!-- CSS here -->
	<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css"> -->
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/tailwind.min.css">
</head>
<body class="h-screen overflow-hidden flex items-center justify-center" style="background: #edf2f7;">

<div class="container max-w-full mx-auto py-24 px-6">
  <div class="font-sans">
  <div class="max-w-sm mx-auto px-6">
    <div class="relative flex flex-wrap">
      <div class="w-full relative">
        <div class="mt-6">
          <div" class="mt-8">
            <div class="mx-auto max-w-lg">
              <div class="bg-white mt-4 px-4 py-3 rounded-lg shadow-md">
				<div class="flex pt-6 pb-6 items-center justify-between">
					<span class=" text-center font-medium text-sm">We have sent you an email, please follow the click there to verify yourself.</span>
				</div>
			  </div>
              
              <a href="<?php echo DOMAIN ?>login" class="mt-3 text-center text-lg font-semibold bg-gray-800 w-full text-white rounded-lg px-6 py-3 block shadow-xl hover:text-white hover:bg-black">Home</a>
            </div>
          </div>
       
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</body>
</html>
