<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo TITLE ?></title>
	<link href="<?php echo DOMAIN ?>assets/img/favicon.ico" rel="shortcut icon"/>
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/tailwind.min.css">
</head>
<body class="flex items-center justify-center" style="background: #edf2f7;">